In [109]:
import pandas as pd

In [110]:
WIP_AGEING_URL = "/mnt/c/Users/Admin/OneDrive/Desktop/Practice/WIP_Ageing.xlsx"
CUSTOMER_MASTER = "/mnt/c/Users/Admin/OneDrive/Desktop/Practice/Customer_Master.xlsx"

In [111]:
wip_ageing_df = pd.read_excel(WIP_AGEING_URL)
customer_master_df = pd.read_excel(CUSTOMER_MASTER)

In [112]:
pd.set_option('display.max_rows', None)    
pd.set_option('display.max_columns', None)   
pd.set_option('display.width', None)         
pd.set_option('display.max_colwidth', None)

In [113]:
wip_ageing_df.head()

,Cust,SvcOrder,DateIn,ManuPartNo,Tot_Amt
0,A502109-00,32467557,2025-05-10 00:00:00,201582001-040,11061.6280
1,A502109-00,32467558,2025-05-10 00:00:00,201582002-040,10913.4075
2,A502109-00,32467559,2025-05-10 00:00:00,D23757550-7,7445.7660
3,A502107-00,32467437,2025-05-05 00:00:00,453-5060,809.6565
4,A502102-00,32467401,2025-05-03 00:00:00,D23757500-9,24646.3065

In [114]:
customer_master_df.head()

  Old_Cust_Code New_Cust_Code
0        100013    A100007-02
1        100018    A100001-00
2        100019    A500462-00
3        100040    A100002-00
4        100227    A100006-02

In [115]:
wip_ageing_df.info()
wip_ageing_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2375 entries, 0 to 2374
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Cust        2375 non-null   object
 1   SvcOrder    2375 non-null   object
 2   DateIn      2375 non-null   object
 3   ManuPartNo  2375 non-null   object
 4   Tot_Amt     2375 non-null   float64
dtypes: float64(1), object(4)
memory usage: 92.9+ KB

            Tot_Amt
count  2.375000e+03
mean   2.243148e+04
std    3.754417e+05
min    9.500000e+01
25%    7.147860e+02
50%    2.654429e+03
75%    6.752940e+03
max    1.811002e+07

In [116]:
customer_master_df.info()
customer_master_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Old_Cust_Code  374 non-null    object
 1   New_Cust_Code  374 non-null    object
dtypes: object(2)
memory usage: 6.0+ KB

       Old_Cust_Code New_Cust_Code
count            374           374
unique           373           362
top       A501884-00    A500434-00
freq               2             3

In [117]:
#Requirements 1: 
mapping_dict = dict(zip(customer_master_df["Old_Cust_Code"], customer_master_df["New_Cust_Code"]))
wip_ageing_df["New_Cust"] = wip_ageing_df["Cust"].map(mapping_dict).fillna(wip_ageing_df["Cust"])
wip_ageing_df.head()

,Cust,SvcOrder,DateIn,ManuPartNo,Tot_Amt,New_Cust
0,A502109-00,32467557,2025-05-10 00:00:00,201582001-040,11061.6280,AD502109-00
1,A502109-00,32467558,2025-05-10 00:00:00,201582002-040,10913.4075,AD502109-00
2,A502109-00,32467559,2025-05-10 00:00:00,D23757550-7,7445.7660,AD502109-00
3,A502107-00,32467437,2025-05-05 00:00:00,453-5060,809.6565,A502107-00
4,A502102-00,32467401,2025-05-03 00:00:00,D23757500-9,24646.3065,A502102-00

In [118]:
#check unique value in the column New_Cust in order to indentify the method to extract
unique_new_cust = wip_ageing_df['New_Cust'].unique()
unique_new_cust

array(['AD502109-00', 'A502107-00', 'A502102-00', 'A502100-00',
       'A502069-00', 'A502033-00', 'A501905-00', 'A501784-00',
       'A501768-00', 'A501747-00', 'A501742-00', 'A501738-00',
       'A501666-00', 'A501665-00', 'A501516-01', 'A501512-02',
       'A501503-00', 'A501483-00', 'A501442-00', 'A501369-00',
       'A501364-00', 'A501345-00', 'A501325-01', 'A501220-01',
       'A501130-00', 'A501097-01', 'A501043-00', 'A500806-00',
       'A500792-00', 'A500738-001', 'A500717-00', 'A500712-00',
       'CR500710-01', 'A500689-00', 'A500674-00', 'A500602-00',
       'A500600-00', 'A500554-00', 'A500518-00', 'A500516-00',
       'A500507-00', 'A500495-00', 'A500494-00', 'A500485-00',
       'A500482-00', 'A500477-00', 'A500467-01', 'A500441-00',
       'A500433-01', 'A500415-02', 'A500374-01', 'A500318-03',
       'A500274-01', 'A500223-01', 'A500220-02', 'A500220-01',
       'A500213-01', 'A500193-01', 'A500167-01', 'A500165-01',
       'A500159-02', 'A500151-00', 'A500129-03', 'A500107-00',
       'A500097-00', 'A500089-00', 'A500087-00', 'A500082-03',
       'A500081-00', 'A500072-01', 'A500070-00', 'A500054-01',
       'A500043-01', 'A500033-01', 'A500031-01', 'A500030-01',
       'A500024-00', 'A500023-00', 'A500021-01', 'A500014-03',
       'A500011-01', 'A400003-24', 'A400001-07', 'A400001-05',
       'A400001-04', 'A400001-02', 'A300009-00', 'A200025-00',
       'A200018-00', 'A200007-00', 'A200005-13', 'A200004-00',
       'A200003-00', 'A200001-00', 'A200001-001', 'A100014-02',
       'A000002-04'], dtype=object)

In [119]:
# the second requirements make me confused that I view the data and I realize the value in the "New_Cust" have 6 -digits before the "-" character. Therefore, I
# to get 6 digits.
# using regex to extract alphabets character and numbers
alphabet_character_regex = '([A-Za-z]+)' #if you want to get alphabet characters
nnumeric_character_regex = '(\d+)' #if you want to get numeric characters
wip_ageing_df_step2 = wip_ageing_df.copy()
wip_ageing_df_step2['6-digit'] = wip_ageing_df_step2["New_Cust"].str.split("-").str[0].str.extract(nnumeric_character_regex)
wip_ageing_df_step2.head()

,Cust,SvcOrder,DateIn,ManuPartNo,Tot_Amt,New_Cust,6-digit
0,A502109-00,32467557,2025-05-10 00:00:00,201582001-040,11061.6280,AD502109-00,502109
1,A502109-00,32467558,2025-05-10 00:00:00,201582002-040,10913.4075,AD502109-00,502109
2,A502109-00,32467559,2025-05-10 00:00:00,D23757550-7,7445.7660,AD502109-00,502109
3,A502107-00,32467437,2025-05-05 00:00:00,453-5060,809.6565,A502107-00,502107
4,A502102-00,32467401,2025-05-03 00:00:00,D23757500-9,24646.3065,A502102-00,502102

In [120]:
#the third requirement
# Sort and drop duplicates base on ManuPartNo
wip_ageing_df_step2 = wip_ageing_df_step2.sort_values(by=['ManuPartNo', 'DateIn'], ascending=[True, False])
wip_ageing_df_step3 = wip_ageing_df_step2.drop_duplicates(subset=["ManuPartNo"], keep="first")
wip_ageing_df_step3.head()

,Cust,SvcOrder,DateIn,ManuPartNo,Tot_Amt,New_Cust,6-digit
2241,A200001-00,32467578,2025-05-10 00:00:00,2758,1362.2070,A200001-00,200001
1963,A200004-00,32462148,2024-10-14 00:00:00,6301,5312.3055,A200004-00,200004
1990,A200004-00,32460763,2024-08-28 00:00:00,8347,1506.2795,A200004-00,200004
1999,A200004-00,32463942,2024-12-16 00:00:00,8544,326.1540,A200004-00,200004
926,A400001-02,32466371,2025-03-23 00:00:00,11700,220.6110,A400001-02,400001

In [121]:
wip_ageing_df_step4 = wip_ageing_df_step3.copy()
# this step I will calculate the timestamp today and add  a new column ts_time of DateIn. I will Subtract both and get the result 
# and transform to months ttype and classtification into age buckets.  
AVERAGE_DAY_PER_MONTH = 30
wip_ageing_df_step4['ts_time'] = pd.to_datetime(wip_ageing_df_step4['DateIn']).dt.normalize()
today_ts = pd.Timestamp.today().normalize()
wip_ageing_df_step4['months_diff'] = ((today_ts - wip_ageing_df_step4['ts_time']).dt.days / AVERAGE_DAY_PER_MONTH).round(2)  # Average days in a month
# Define the Swith function to categorize into age buckets
bins = [0, 9, 12, 13, 24, 25, float('inf')]  # Khoảng: <9, 9-12, 12-13, 13-24, 24-25, >25
labels_value = ["BELOW09MTHS", ">09TO12MTHS", ">12TO13MTHS", ">13TO24MTHS", ">24TO25MTHS", ">25MTHS"]
wip_ageing_df_step4['Age_Bucket'] = pd.cut(wip_ageing_df_step4['months_diff'], bins=bins, labels=labels_value, right=False)  # right=False để <9 là exclusive

wip_ageing_df_step4.head()

,Cust,SvcOrder,DateIn,ManuPartNo,Tot_Amt,New_Cust,6-digit,ts_time,months_diff,Age_Bucket
2241,A200001-00,32467578,2025-05-10 00:00:00,2758,1362.2070,A200001-00,200001,2025-05-10,10.73,>09TO12MTHS
1963,A200004-00,32462148,2024-10-14 00:00:00,6301,5312.3055,A200004-00,200004,2024-10-14,17.67,>13TO24MTHS
1990,A200004-00,32460763,2024-08-28 00:00:00,8347,1506.2795,A200004-00,200004,2024-08-28,19.23,>13TO24MTHS
1999,A200004-00,32463942,2024-12-16 00:00:00,8544,326.1540,A200004-00,200004,2024-12-16,15.57,>13TO24MTHS
926,A400001-02,32466371,2025-03-23 00:00:00,11700,220.6110,A400001-02,400001,2025-03-23,12.33,>12TO13MTHS

In [124]:
# Data Quality Check Functions 
# I will check some case to evaluate the data quality of the final dataframe. 
# #I will check some case such as null value, duplicate value, 6-digit value and numeric only value.
import pandas as pd
import numpy as np

def check_not_null(df, columns): 
    """
    Check for null values in specified columns.
    Returns a dict with column names as keys and count of nulls as values.
    """
    null_counts = {}
    for col in columns:
        if col in df.columns:
            null_counts[col] = df[col].isnull().sum()
        else:
            null_counts[col] = f"Column '{col}' not found in DataFrame"
    return null_counts

def check_duplicate_rows(df): #all columns
    """
    Check for completely duplicate rows.
    Returns a dict with total duplicates and list of duplicate indices.
    """
    duplicates = df[df.duplicated(keep=False)]
    duplicate_indices = duplicates.index.tolist()
    return {
        'total_duplicates': len(duplicate_indices),
        'duplicate_indices': duplicate_indices,
        'duplicate_rows': duplicates
    }

def check_exactly_6_digits(df, column): # To check 6-digit	
    """
    Check if values in the column are exactly 6 digits (numeric characters).
    Returns a dict with count of valid/invalid and list of invalid indices.
    """
    if column not in df.columns:
        return f"Column '{column}' not found in DataFrame"
    
    # Convert to string and check length and if all digits
    is_6_digits = df[column].astype(str).str.match(r'^\d{6}$')
    invalid_indices = df[~is_6_digits].index.tolist()
    return {
        'valid_count': is_6_digits.sum(),
        'invalid_count': (~is_6_digits).sum(),
        'invalid_indices': invalid_indices,
        'invalid_values': df.loc[invalid_indices, column].tolist()
    }

def check_numeric_only(df, column): # To check ManuPartNo, SvcOrder, Tot_Amt
    """
    Check if values in the column contain only numeric characters (digits).
    Returns a dict with count of valid/invalid and list of invalid indices.
    """
    if column not in df.columns:
        return f"Column '{column}' not found in DataFrame"
    
    # Check if string representation is all digits
    is_numeric = df[column].astype(str).str.isdigit()
    invalid_indices = df[~is_numeric].index.tolist()
    return {
        'valid_count': is_numeric.sum(),
        'invalid_count': (~is_numeric).sum(),
        'invalid_indices': invalid_indices,
        'invalid_values': df.loc[invalid_indices, column].tolist()
    }

def run_data_quality_checks(df, columns_to_check_null=None, digit_column=None, numeric_column=None):
    """
    Run all data quality checks and return a summary report.
    """
    report = {}
    
    # Check not null
    if columns_to_check_null:
        report['null_checks'] = check_not_null(df, columns_to_check_null)
    

    # Check duplicates
    report['duplicate_rows'] = check_duplicate_rows(df)

    # Check 6 digits
    if digit_column:
        report['6_digits_check'] = check_exactly_6_digits(df, digit_column)

    # Check numeric only
    if numeric_column:
        report['numeric_only_check'] = check_numeric_only(df, numeric_column)

    return report


columns_to_check = ['New_Cust', '6-digit', 'DateIn', 'Age_Bucket']
quality_report = run_data_quality_checks(
    wip_ageing_df_step4, 
    columns_to_check_null=columns_to_check, 
    digit_column='6-digit', 
    numeric_column='6-digit'
)
print(quality_report)

{'null_checks': {'New_Cust': np.int64(0), '6-digit': np.int64(0), 'DateIn': np.int64(0), 'Age_Bucket': np.int64(0)}, 'duplicate_rows': {'total_duplicates': 0, 'duplicate_indices': [], 'duplicate_rows': Empty DataFrame
Columns: [Cust, SvcOrder, DateIn, ManuPartNo, Tot_Amt, New_Cust, 6-digit, ts_time, months_diff, Age_Bucket]
Index: []}, '6_digits_check': {'valid_count': np.int64(849), 'invalid_count': np.int64(0), 'invalid_indices': [], 'invalid_values': []}, 'numeric_only_check': {'valid_count': np.int64(849), 'invalid_count': np.int64(0), 'invalid_indices': [], 'invalid_values': []}}

In [123]:
# This step I will check som